/*
 * Created on 2021-01-14 ( Date ISO 2021-01-14 - Time 12:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */

package org.demo.data.record;


import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for bean RoleRecord
 * 
 * @author Telosys Tools Generator
 *
 */
public class RoleRecordTest 
{

	@Test
	public void testSettersAndGetters() {
		
		System.out.println("Checking class RoleRecord getters and setters ..." );
		
		RoleRecord roleRecord = new RoleRecord();


		//--- Test setter/getter for attribute "myfield"  ( model type : String / wrapperType : String )
		roleRecord.setMyfield( "A" ) ;
		Assert.assertEquals( "A", roleRecord.getMyfield() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "id"  ( model type : int / wrapperType : Integer )
		roleRecord.setId( 100 ) ;
		Assert.assertTrue(  100 == roleRecord.getId()  ) ; // Primitive type in model


		//--- Test setter/getter for attribute "creationDate"  ( model type : Date / wrapperType : Date )
		roleRecord.setCreationDate( java.sql.Date.valueOf("2001-06-22") ) ;
		Assert.assertEquals( java.sql.Date.valueOf("2001-06-22"), roleRecord.getCreationDate() ) ; // Not primitive type in model


		//--- Test setter/getter for attribute "relationship"  ( model type : String / wrapperType : String )
		roleRecord.setRelationship( "A" ) ;
		Assert.assertEquals( "A", roleRecord.getRelationship() ) ; // Not primitive type in model


	}

}
