/*
 * Created on 2021-01-14 ( Date ISO 2021-01-14 - Time 12:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;

import java.util.Date;

/**
 * Java bean for entity "Role" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class RoleRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer id ; // int // Id or Primary Key


    private String myfield ;  // String 

    private Date creationDate ;  // Date 

    private String relationship ;  // String 

    /**
     * Default constructor
     */
    public RoleRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "myfield" field value
     * This field is mapped on the database column "myfield" ( type "", NotNull : false ) 
     * @param myfield
     */
    public void setMyfield( String myfield ) {
        this.myfield = myfield;
    }
    /**
     * Get the "myfield" field value
     * This field is mapped on the database column "myfield" ( type "", NotNull : false ) 
     * @return the field value
     */
    public String getMyfield() {
        return this.myfield;
    }

    /**
     * Set the "creationDate" field value
     * This field is mapped on the database column "creationDate" ( type "", NotNull : false ) 
     * @param creationDate
     */
    public void setCreationDate( Date creationDate ) {
        this.creationDate = creationDate;
    }
    /**
     * Get the "creationDate" field value
     * This field is mapped on the database column "creationDate" ( type "", NotNull : false ) 
     * @return the field value
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Set the "relationship" field value
     * This field is mapped on the database column "relationship" ( type "", NotNull : false ) 
     * @param relationship
     */
    public void setRelationship( String relationship ) {
        this.relationship = relationship;
    }
    /**
     * Get the "relationship" field value
     * This field is mapped on the database column "relationship" ( type "", NotNull : false ) 
     * @return the field value
     */
    public String getRelationship() {
        return this.relationship;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(myfield);
        sb.append("|");
        sb.append(id);
        sb.append("|");
        sb.append(creationDate);
        sb.append("|");
        sb.append(relationship);
        return sb.toString(); 
    } 



}
