/*
 * Created on 2021-01-14 ( Date ISO 2021-01-14 - Time 12:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.data.record.listitem;

import org.demo.data.record.RoleRecord;
import org.demo.commons.ListItem;

public class RoleListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public RoleListItem(RoleRecord role) {
		super();

		this.value = ""
			 + role.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = role.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
