/*
Generated by Jthereum BETA version!
┌──────────────┬──────────────────────────────┐
│     Atribute │                        Value │
├──────────────┼──────────────────────────────┤
│      Version │           2.1.3.384.release1 │
│         Beta │                         true │
│ Build Number │                          384 │
│   Build Date │ Fri Jun 19 15:57:40 HST 2020 │
│   Short Hash │                 13a5f6d8e22c │
│ Installation │ 0x215842b67940242066cf7fef01 │
└──────────────┴──────────────────────────────┘

*/
pragma solidity ^0.5.9;
contract App
{
	string private greeting = string("Hi");
	address private owner;
	constructor() public 
	{
		owner = msg.sender;
	}
	function onlyOwner() public view 
	{
		require(isOwner(), "Only owner can do that!");
	}
	function isOwner() public view returns (bool) 
	{
		return (msg.sender == owner);
	}
	function setGreeting(string memory _newGreeting) public 
	{
		onlyOwner();
		greeting = _newGreeting;
	}
	function sayHello() public view returns (string memory) 
	{
		if (isOwner()) 
		{
			return "Hey";
		} else 
		{
			return greeting;
		}
	}
	int32 private value;
	function setValue(int32 newValue) public 
	{
		value = newValue;
	}
	function getValue() public view returns (int32) 
	{
		return value;
	}



}
