/*
Generated by Jthereum BETA version!
┌──────────────┬──────────────────────────────┐
│     Atribute │                        Value │
├──────────────┼──────────────────────────────┤
│      Version │           2.1.3.384.release1 │
│         Beta │                         true │
│ Build Number │                          384 │
│   Build Date │ Fri Jun 19 15:57:40 HST 2020 │
│   Short Hash │                 13a5f6d8e22c │
│ Installation │ 0x215842b67940242066cf7fef01 │
└──────────────┴──────────────────────────────┘

*/
pragma solidity ^0.5.9;
contract SelfDestruct
{
	address payable private creator;
	uint private iteration;

	constructor() public 
	{
		creator = msg.sender;
		iteration = 0;
	}
	function incrementValue() public 
	{
		(iteration ++);
	}
	function getIteration() public view returns (uint) 
	{
		return iteration;
	}
	function kill() public 
	{
		if ((msg.sender == creator)) 
		{
			selfdestruct(creator);
		}
	}

}
