/*
 * Created on 2021-01-14 ( Date ISO 2021-01-14 - Time 12:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.fake;

import org.demo.persistence.RolePersistence ;
import org.demo.persistence.RolePersistenceGenericTest;
import org.junit.Test;

/**
 * JUnit tests for Role persistence service
 * 
 * @author Telosys Tools
 *
 */
public class RolePersistenceFakeTest extends RolePersistenceGenericTest {

	@Test
	public void testPersistenceService() {
    	System.out.println("test RolePersistenceFake ");

    	RolePersistence persistenceService = new RolePersistenceFake();

    	testPersistenceServiceWithAutoincrementedKey(persistenceService);

	}	
}
