/*
 * Created on 2021-01-14 ( Date ISO 2021-01-14 - Time 12:43:55 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.1.2
 */
package org.demo.persistence.impl.fake;

import java.util.List;


import javax.inject.Named;

import org.demo.data.record.RoleRecord;
import org.demo.persistence.RolePersistence;
import org.demo.persistence.impl.fake.commons.GenericFakeDAO;

/**
 * Role persistence service - FAKE implementation 
 * 
 * @author Telosys
 *
 */
@Named("RolePersistence")
public class RolePersistenceFake extends GenericFakeDAO<RoleRecord> implements RolePersistence {

	/**
	 * Constructor
	 */
	public RolePersistenceFake() {
		super(RoleRecord.class);
	}

	/**
	 * Creates a new bean instance and set its primary key value(s)
	 * 
	 * @param id
	 * @return the new instance
	 */
	private RoleRecord newInstanceWithPrimaryKey(int id) {
		RoleRecord record = new RoleRecord();
        record.setId(id); 
		return record;
	}

	//-------------------------------------------------------------------------------------
	// Generic DAO abstract methods implementations
	//-------------------------------------------------------------------------------------
	@Override
	protected String getKey(RoleRecord record) {
		return buildKeyString(record.getId());
	}
	
	@Override
	protected void setAutoIncrementedKey(RoleRecord record, long value) {
		record.setId(toInt(value));
	}

	//-------------------------------------------------------------------------------------
	// Persistence interface implementations
	//-------------------------------------------------------------------------------------
	@Override
	public long countAll() {
		return super.doCountAll();
	}
	
	@Override
	public RoleRecord create(RoleRecord record) {
		super.doCreateAutoIncremented(record);
		return record;
	}

	@Override
	public boolean delete(RoleRecord record) {
		return super.doDelete(record);
	}

	@Override
	public boolean deleteById(Integer id) {
		RoleRecord record = newInstanceWithPrimaryKey(id);
		return super.doDelete(record);
	}

	@Override
	public boolean exists(RoleRecord record) {
		return super.doExists(record);
	}

	@Override
	public boolean exists(Integer id) {
		RoleRecord record = newInstanceWithPrimaryKey(id);
		return super.doExists(record);
	}

	@Override
	public List<RoleRecord> findAll() {
		return super.doFindAll();
	}

	@Override
	public RoleRecord findById(Integer id) {
        RoleRecord record = newInstanceWithPrimaryKey(id);
		return super.doFind(record);
	}

	@Override
	public RoleRecord save(RoleRecord record) {
		if (super.doExists(record)) {
			super.doUpdate(record);
		} else {
			super.doCreateAutoIncremented(record);
		}
        return record;
	}

	@Override
	public boolean update(RoleRecord record) {
		return super.doUpdate(record);	
	}
}
